#define DOZENOS_SUCCESS 0
#define DOZENOS_GENERAL_FAILURE 1
#define DOZENOS_INVALID_PATH 2
#define DOZENOS_EMPTY_CONFIG 3
#define DOZENOS_CONFIG_PARSE_ERROR 4
#define DOZENOS_COMMIT_FAILURE 5
#define DOZENOS_PARTIAL_COMMIT 6
